# Generated by Django 6.0.2 on 2026-04-13 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default='09:30:00'),
            preserve_default=False,
        ),
    ]
